### PR TITLE
Update _DDFunctionEvaluator.m

### PR DESCRIPTION
**Pull request by SheffieldKevin**
Added the atan2 function.

### CODE REVIEW

**Comment by davedelong** [comment]
This looks great! What do you think about an implementation in [the Precision evaluator](https://github.com/davedelong/DDMathParser/blob/master/DDMathParser/_DDPrecisionFunctionEvaluator.m#L419) as well?

**Comment by SheffieldKevin** [comment]
I've not looked at the precision evaluator as I have not needed it, but I would guess for consistency it is probably a good idea.

**Comment by SheffieldKevin** [comment]
Implementation based on [wikipedia atan2](http://en.wikipedia.org/wiki/Atan2) looks not to bad which would just build on your DDDecimalAtan function. I'm not sure how comfortable I would be doing it as I would not then be using it and it would remain untested..

**Comment by SheffieldKevin** [comment]
I have added the NSDecimal version of Atan2. It is not tested. I couldn't see any tests that related to the NSDecimal implementation & I've never used SenTestKit. I leave it to your discretion to include or not.

**Comment by davedelong** [comment]
I've put `atan2` into the 2.0 branch, which will be merged into master soon.

**Pull request closed without merging**
