### PR TITLE
Upgrade to Swift 5

### PR DESCRIPTION
**Pull request by ffried**
This updates the project to Swift 5 and Xcode 10.2.

### CODE REVIEW

**Comment by davedelong** [comment]
Sanity check: Any change in how the unit tests pass? (I believe there's one failing that I'm investigating, slowly)

**Comment by ffried** [comment]
@davedelong I think I've let them run and they passed, but let me just quickly check again

**Comment by ffried** [comment]
Yep, all green (on both Mac and iOS simulator).
image

**Comment by davedelong** [comment]
Awesome. Thanks, @ffried!

**Pull request merged**
